<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;net8.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>ZeroPlatform.Charts</AssemblyName>
    <RootNamespace>ZeroPlatform.Charts</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net462'">
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Include="System.Buffers" Version="4.5.1" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ZeroGraphics.Core" Version="1.0.1" />
    <PackageReference Include="ZeroGraphics.DirectX" Version="1.0.1" />
    <PackageReference Include="ZeroGraphics.Direct2D" Version="1.0.1" />
    <PackageReference Include="ZeroGraphics.Waveform" Version="1.0.1" />
    <PackageReference Include="ZeroUI.Core" Version="1.5.0" />
  </ItemGroup>
</Project>
